Support for the absence of Hugo's FrontMatter
riita10069/md-translate pull request #7
Opened 2023-04-03 02:10 UTC by riita10069

2023-04-03 17:53 UTC, yurimarimo commented
hugo header 処理のオプション化、ありがとう！

なぜかsuggestionできなかったのでコメントで言います。
pathでファイル指定された場合に実行される108-110行目
```
translate_page(
                path.removesuffix('.md') if src_lang == const.LANG_EN else path.removesuffix('.' + src_lang + '.md'),
                src_lang, dest_lang, output, debug)
```
この場所で is_hugo が引数として設定されていないので含めてください！他はLGTMです(って言ってみたかったw)！

あとはconflictの解消をお願いします:pray:

一つ提案なんだけど、workshopを翻訳する場合は基本的にこの `--hugo` オプションを付けることになるだろうから、その旨を README に書くのはどうだろう？
私は恥ずかしながらこの翻訳ツールを作るまで hugo というフレームワークを知らなくて、このツールを使う人で hugo のことを知らない場合も多いと思うので、「workshopを翻訳する際には必要です」程度の補足があってもいいかなと思った。

2023-04-03 17:54 UTC, yurimarimo requested changes
hugo header 処理のオプション化、ありがとう！

なぜかsuggestionできなかったのでコメントで言います。
pathでファイル指定された場合に実行される108-110行目

```
translate_page(
                path.removesuffix('.md') if src_lang == const.LANG_EN else path.removesuffix('.' + src_lang + '.md'),
                src_lang, dest_lang, output, debug)
```
この場所で is_hugo が引数として設定されていないので含めてください！他はLGTMです(って言ってみたかったw)！

あとはconflictの解消をお願いします🙏

2023-04-06 07:10 UTC, yurimarimo approved these changes

2023-04-06 07:11 UTC, Coresummer approved these changes
LGTM

2023-04-06 07:11 UTC, merged